from tkinter import *
def mile_to_kilometre():
    miles =float(miles_input.get())
    km = miles * 1.609
    kilometre_result_label.config(text=f"{km}")
window = Tk()
window.title("Miles to Kilometres Converter")
window.config(padx=20, pady=20)
miles_input = Entry(width=7)
miles_input.grid(row=0, column=1)
miles_label = Label(text="Miles")
miles_label.grid(row=0, column=2)
is_equal_label = Label(text="is equal to")
is_equal_label.grid(row=1, column=0)
kilometre_result_label = Label(text="0")
kilometre_result_label.grid(row=1, column=1)
kilometre_label = Label(text="km")
kilometre_label.grid(row=1, column=2)
calculate_button = Button(text="Calculate",command=mile_to_kilometre)
calculate_button.grid(row=3, column=1)
window.mainloop()
